version: "3"
services:
    psql:
      image: postgres:9.6.2
      environment:
        - POSTGRES_USER=promoserver
        - POSTGRES_PASSWORD=promoserver
        - POSTGRES_DB=promoserver
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - /data/postgres:/var/lib/postgresql/data/pgdata
      networks:
        - back-tier

    web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      environment:
        - NODE_ENV=docker
      networks:
        - back-tier
      depends_on:
        - psql
      links:
        - psql
        - ipfs
      command: bash -c 'while !</dev/tcp/psql/5432; do sleep 10; done; npm start'

    ipfs:
      image: ipfs/go-ipfs:latest
      ports:
         - "8088:8080"
         - "5001:5001"
         - "4001:4001"
      environment:
         - IPFS_BIND_IP=0.0.0.0
         - IPFS_BOOTSTRAP_RM_ALL=true
         - GATEWAY_PORT=8080
         - API_PORT=5001
      volumes:
         - /data/
      networks:
        - back-tier

networks:
  back-tier:

