version: "3"

services:
    psql:
      restart: always
      image: postgres:9.6.2
      environment:
        POSTGRES_USER: promoserver
        POSTGRES_PASSWORD: promoserver
        POSTGRES_DB: promoserver
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - /Users/shicong/sWorkSpace/docker_volume/pg_data/data:/var/lib/postgresql/data/pgdata
      networks:
        - back-tier

    web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      environment:
        POSTGRES_USER: promoserver
        POSTGRES_PASSWORD: promoserver
        POSTGRES_DB: promoserver
      networks:
        - back-tier
      links:
        - psql

networks:
  back-tier:

